shiny_app_template <- function(app_name, author = Sys.info()[['user']]) {
  author <- paste('#', author)
  orig_date <- paste('# Original date:', Sys.Date())
  run_on <- paste0('# Written/run on RStudio ' , RStudio.Version()$mode, ' ',
                   RStudio.Version()$version, ' and R ',
                   version$major, '.', version$minor)

  r_code <- c(
    '##########################################################',
    '# Name of app',
    author,
    orig_date,
    run_on,
    '# Description of content',
    '##########################################################',
    '',
    '',
    '# Get packages',
    'source("setup.R")',
    '',
    '# UI',
    'ui <- fluidPage(',
    'tagList(',
    '# Specify most recent fontawesome library - change version as needed',
    'tags$style("@import url(https://use.fontawesome.com/releases/v6.1.1/css/all.css);"),',
    'navbarPage(',
    '    id = "intabset", # id used for jumping between tabs',
    '    title = div(',
    '        tags$a(img(src = "phs-logo.png", height = 40),',
    '               href = "https://www.publichealthscotland.scot/",',
    '               target = "_blank"), # PHS logo links to PHS website',
    '    style = "position: relative; top: -5px;"),',
    paste0('    windowTitle = ', '"', app_name,  '"',  ",", '# Title for browser tab'),
    '    header = tags$head(includeCSS("www/styles.css"),  # CSS stylesheet',
    '    tags$link(rel = "shortcut icon", href = "favicon_phs.ico") # Icon for browser tab',
    '),',
    '##############################################.',
    '# INTRO PAGE ----',
    '##############################################.',
    'tabPanel(title = "Introduction",',
    '    icon = icon_no_warning_fn("circle-info"),',
    '    value = "intro",',
    '',
    '    h1("Welcome to the dashboard"),',
    '    uiOutput("intro_page_ui")',
    '',
    '), # tabpanel',
    '##############################################.',
    '# PAGE 1 ----',
    '##############################################.',
    'tabPanel(title = "Page 1",',
    '    # Look at https://fontawesome.com/search?m=free for icons',
    '    icon = icon_no_warning_fn("stethoscope"),',
    '    value = "intro",',
    '',
    '    h1("Page 1 title"),',
    '    uiOutput("intro_page_ui")',
    '',
    '    ) # tabpanel',
    '    ) # navbar',
    '  ) # taglist',
    ') # ui fluidpage',
    '',
    '# ----------------------------------------------',
    '# Server',
    '',
    'server <- function(input, output, session) {',
    '',
    '    # Get functions',
    '    source(file.path("functions/core_functions.R"), local = TRUE)$value',
    '    source(file.path("functions/intro_page_functions.R"), local = TRUE)$value',
    '    source(file.path("functions/page_1_functions.R"), local = TRUE)$value',
    '',
    '    # Get content for individual pages',
    '    source(file.path("pages/intro_page.R"), local = TRUE)$value',
    '    source(file.path("pages/page_1.R"), local = TRUE)$value',
    '',
    '}',
    '',
    '# Run the application',
    'shinyApp(ui=ui, server=server)',
    '',
    '### END OF SCRIPT ###'
  )
  r_code <- paste(r_code, collapse = '\n')

  return(r_code)
}
