on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

name: phs_checks.yaml

jobs:
  PHS-checks:
    uses: Public-Health-Scotland/actions/.github/workflows/phs_package_checks.yaml@v1.4.0
    permissions: write-all
    secrets: inherit
